development:
  adapter: mysql2
  encoding: utf8
  database: events_calendar_berlin_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: events_calendar_berlin_test
  username: root
  password:
