development:
  adapter: mysql2
  encoding: utf8
  database: eventscalendarberlin_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: eventscalendarberlin_test
  username: root
  password:
